version: '3.2'

services:
  cron_server:
    image: 223455578796.dkr.ecr.us-west-2.amazonaws.com/monitor-stress:latest
    restart: always
    container_name: stress
    volumes:
      - $PWD/config/stressTests.json:/user/app/config/stressTests.json
      - $PWD/config/system.yml:/metricbeat-7.4.1-linux-x86_64/modules.d/system.yml:ro
    ports:
      - "3000:3000"
    extra_hosts:
      - "logstash:${ADDRESS}"
